### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by mtlynch** [szazo/DHT11_Python#2]
Thanks for your work on this project. Would it be possible to add an open source license so that others can include this into their project legally? An open license such as Apache2 or MIT would be great.

See Github's help page:

https://help.github.com/articles/open-source-licensing/

tl;dr - It mainly consists of picking a license and putting the text in a LICENSE.md file of your repo.

**Comment by szazo** [comment]
Thanks for the info @mtlynch, I added MIT license.
