### ISSUE TITLE
Make DHT11_Python a pip package

### ISSUE THREAD

**Issue by blakev** [szazo/DHT11_Python#6]
You should make this a pip installable package, `rpi-dht11`.

I can make a pull request if you'd be willing to manage the pypi project.

**Comment by szazo** [comment]
Sure, it sounds great, please proceed with the request.

**Comment by scollis** [comment]
Also need to populate with setup.py et al.. This would mean moving the base code into a subdir.. @blakev are you still working on that? I would also like to link to BerryConda https://github.com/jjhelmus/berryconda

**Comment by obains** [comment]
+1 for creating a setup.py. 
if @blakev is not doing it, I can have a look (but not so experienced with this sort of stuff).

**Comment by dragoneena12** [comment]
Hi @szazo 
I want to make it easier to use this library by register PyPI. 
Can I work on this?

**Comment by szazo** [comment]
> Hi @szazo
> I want to make it easier to use this library by register PyPI.
> Can I work on this?

Dear @dragoneena12,

Sure :) Do you need anything from me for that, or enough if I will merge your pull request?

Thanks
Zoli

**Comment by dragoneena12** [comment]
@szazo 
I uploaded this package to PyPI and now we can install this library just by `pip install dht11` !
Now the maintainer of PyPI project is just me, so please register PyPI and tell me your username. Then I will add you as project owner.
I will make pull request to update `readme.md` later. Thanks!

**Comment by szazo** [comment]
My username is szazo on pypi. Thank you :)

**Comment by dragoneena12** [comment]
I added you as a project owner. Thanks :)
