### ISSUE TITLE
give thanks

### ISSUE THREAD

**Issue by mohsen8156** [szazo/DHT11_Python#8]
Hi szazo,
I'm a beginner programmer and have a raspberry pi3. I'm at 16.
I bought a DHT11 sensor. I wanted to work by its with python, but there wasn't a good source.
Then I find you in a raspberrypi topic.
Thanks a lot because of this module.
Please see my page on github https://github.com/mohsen8156 and share your ideas about my projects.
Thanks. :)

**Comment by szazo** [comment]
Dear @mohsen8156, thank you very much for your feedback :)
