### ISSUE TITLE
Wrong temperature and humid values

### ISSUE THREAD

**Issue by sachithmuhandiram** [szazo/DHT11_Python#9]
When I execute the given program, I am getting 

**Temperature: 0 C
Humidity: 1 %**

**Comment by mountainash** [comment]
Must be either very cold where you are, or I'm guessing your sensor has an issue.

**Comment by sachithmuhandiram** [comment]
> Must be either very cold where you are, or I'm guessing your sensor has an issue.

Temperature not 0, as we have tropical weather.

Sensor gave right values later. May be a problem with connectivity or sensor.
Thanks for your feedback.
